name: Test Deployment
run-name: dev runner
on: push

env:
  IMAGE_NAME: europe-west4-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/storeinformationdatabase-repository/storeinformationdatabase
  VPC_CONNECTOR: projects/${{secrets.GCP_PROJECT_ID}}/locations/europe-west4/connectors/eva-modeller
  REGION_ID: europe-west4

jobs:
  dev-deployment:
    runs-on: self-hosted
    container: node:16-alpine
    environment: dev

    steps:
    
    - name: Setting up environment for build...
      run: |
       apk add --no-cache git maven bash curl wget
       apk --no-cache add openjdk17-jdk
       apk add --no-cache python3 py3-pip
       
    - name: Checking out the repo...
      uses: actions/checkout@v3
      with:
        ref: development
        
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEYFILE_JSON }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
